[package]
name = "inkjet"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/SomewhereOutInSpace/inkjet/"
description = "A syntax highlighting library based on tree-sitter."
keywords = ["tree-sitter", "syntax", "highlighting", "highlight"]

include  = [
	"/languages/*",
	"/src"
]

[dependencies]
ahash = "0.8.3"
thiserror = "1.0.44"
tree-sitter = "0.20.10"
tree-sitter-highlight = "0.20.1"

[build-dependencies]
anyhow = "1"
cc = "1"
indoc = "2.0.3"
fs_extra = "1.3.0"
rayon = "1.7.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
