[package]
name = "inkjet"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/SomewhereOutInSpace/inkjet/"
description = "A syntax highlighting library based on tree-sitter."
keywords = ["syntax", "highlighting", "highlight", "syntax"]

[dependencies]
tree-sitter = "0.20.10"
tree-sitter-highlight = "0.20.1"

# Languages
tree-sitter-asm = "0.1.0"
tree-sitter-bash = "0.19.0"
tree-sitter-c = "0.20.4"
tree-sitter-c-sharp = "0.20.0"
tree-sitter-cmake = "0.4.0"
tree-sitter-commonlisp = "0.3.0"
tree-sitter-cpp = "0.20.2"
tree-sitter-css = "0.19.0"
tree-sitter-cuda = "0.20.3"
tree-sitter-dart = "0.0.3"
tree-sitter-dockerfile = "0.1.0"
tree-sitter-elisp = "1.3.0"
tree-sitter-elixir = "0.1.0"
tree-sitter-erlang = "0.1.0"
tree-sitter-glsl = "0.1.4"
tree-sitter-go = "0.20.0"
tree-sitter-html = "0.19.0"
tree-sitter-java = "0.20.0"
tree-sitter-javascript = "0.20.0"
tree-sitter-json = "0.19.0"
tree-sitter-kotlin = "0.2.11"
tree-sitter-lua = "0.0.18"
tree-sitter-md = "0.1.5"
tree-sitter-nix = "0.0.1"
tree-sitter-objc = "1.2.0"
tree-sitter-ocaml = "0.20.4"
tree-sitter-openscad = "0.4.2"
tree-sitter-python = "0.20.3"
tree-sitter-r = "0.19.5"
tree-sitter-regex = "0.20.0"
tree-sitter-ruby = "0.20.0"
tree-sitter-scala = "0.20.1"
tree-sitter-sql = "0.0.2"
tree-sitter-swift = "0.3.6"
tree-sitter-toml = "0.20.0"
tree-sitter-typescript = "0.20.2"
tree-sitter-vue = "0.0.3"
