[package]
name = "inkjet"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/SomewhereOutInSpace/inkjet/"
description = "A syntax highlighting library based on tree-sitter."
keywords = ["tree-sitter", "syntax", "highlighting", "highlight"]

include  = [
	"/languages/*/grammar.js",
	"/languages/*/queries",
	"/languages/*/src",
	"/languages/tree-sitter-typescript/typescript/grammar.js",
	"/languages/tree-sitter-typescript/typescript/src",
	"/languages/tree-sitter-typescript/common",
	"/src"
]

[dependencies]
tree-sitter = "0.20.10"
tree-sitter-highlight = "0.20.1"

[build-dependencies]
anyhow = "1"
cc = "1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
