[package]
name = "inkjet"
version = "0.5.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Colonial-Dev/inkjet/"
description = "A batteries-included syntax highlighting library for Rust, based on tree-sitter."
keywords = ["tree-sitter", "syntax", "highlighting", "highlight"]

include  = [
	"/config",
	"/languages/*",
	"/src"
]

[features]
default = ["html"]
html = ["dep:v_htmlescape"]

[dependencies]
once_cell = "1.18.0"
phf = "0.11.2"
thiserror = "1.0.44"
tree-sitter = "0.20.10"
tree-sitter-highlight = "0.20.1"

v_htmlescape = { version = "0.15.8", optional = true }

[build-dependencies]
anyhow = "1"
cc = "1"
indoc = "2.0.3"
fs_extra = "1.3.0"
phf_codegen = "0.11.2"
rayon = "1.7.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
