[[languages]]
name = "ada"
repo = "https://github.com/briot/tree-sitter-ada"

[[languages]]
name = "asm"
pretty_name = "GenericAsm"
repo = "https://github.com/rush-rs/tree-sitter-asm"
command = '''
git clone https://github.com/rush-rs/tree-sitter-asm languages/temp/asm &&
cp languages/temp/asm/queries/asm/* languages/temp/asm/queries
'''

[[languages]]
name = "bash"
repo = "https://github.com/tree-sitter/tree-sitter-bash"

[[languages]]
name = "bibtex"
repo = "https://github.com/latex-lsp/tree-sitter-bibtex"
aliases = ["bib"]

[[languages]]
name = "blueprint"
repo = "https://gitlab.com/gabmus/tree-sitter-blueprint"
aliases = ["blp"]

[[languages]]
name = "c"
repo = "https://github.com/tree-sitter/tree-sitter-c"
aliases = ["h"]

[[languages]]
name = "capnp"
repo = "https://github.com/amaanq/tree-sitter-capnp"

[[languages]]
name = "clojure"
repo = "https://github.com/sogaiu/tree-sitter-clojure"
aliases = ["clj", "cljc"]

[[languages]]
name = "cmake"
pretty_name = "CMake"
repo = "https://github.com/uyha/tree-sitter-cmake"

[[languages]]
name = "c_sharp"
pretty_name = "CSharp"
repo = "https://github.com/tree-sitter/tree-sitter-c-sharp"
aliases = ["c#", "csharp", "cs"]

[[languages]]
name = "commonlisp"
pretty_name = "CommonLisp"
repo = "https://github.com/theHamsta/tree-sitter-commonlisp"
aliases = ["cl", "lisp", "common-lisp"]

[[languages]]
name = "cpp"
repo = "https://github.com/tree-sitter/tree-sitter-cpp"
aliases = ["c++", "hpp", "h++", "cc", "hh"]

[[languages]]
name = "css"
repo = "https://github.com/tree-sitter/tree-sitter-css"

[[languages]]
name = "cue"
repo = "https://github.com/eonpatapon/tree-sitter-cue"

[[languages]]
name = "dart"
repo = "https://github.com/UserNobody14/tree-sitter-dart"

[[languages]]
name = "diff"
repo = "https://github.com/the-mikedavis/tree-sitter-diff"

[[languages]]
name = "dockerfile"
repo = "https://github.com/camdencheek/tree-sitter-dockerfile"
aliases = ["docker"]

[[languages]]
name = "elisp"
repo = "https://github.com/Wilfred/tree-sitter-elisp"
aliases = ["el", "emacs-lisp"]

[[languages]]
name = "elixir"
repo = "https://github.com/elixir-lang/tree-sitter-elixir"
aliases = ["ex", "eex", "exs", "leex"]

[[languages]]
name = "elm"
repo = "https://github.com/elm-tooling/tree-sitter-elm"

[[languages]]
name = "erlang"
repo = "https://github.com/WhatsApp/tree-sitter-erlang"
aliases = ["erl", "hrl", "es", "escript"]

[[languages]]
name = "fortran"
repo = "https://github.com/stadelmanma/tree-sitter-fortran"

[[languages]]
name = "go"
repo = "https://github.com/tree-sitter/tree-sitter-go"
aliases = ["golang"]

[[languages]]
name = "gdscript"
pretty_name = "GDScript"
repo = "https://github.com/PrestonKnopp/tree-sitter-gdscript"
aliases = ["gd"]

[[languages]]
name = "glsl"
repo = "https://github.com/theHamsta/tree-sitter-glsl"

[[languages]]
name = "haskell"
repo = "https://github.com/tree-sitter/tree-sitter-haskell"
aliases = ["hs"]

[[language]]
name = "hcl"
repo = "https://github.com/MichaHoffmann/tree-sitter-hcl"
aliases = ["terraform"]

[[languages]]
name = "html"
repo = "https://github.com/tree-sitter/tree-sitter-html"
aliases = ["htm"]

[[languages]]
name = "java"
repo = "https://github.com/tree-sitter/tree-sitter-java"

[[languages]]
name = "javascript"
repo = "https://github.com/tree-sitter/tree-sitter-javascript"
aliases = ["js"]

[[languages]]
name = "json"
repo = "https://github.com/tree-sitter/tree-sitter-json"

[[languages]]
name = "julia"
repo = "https://github.com/tree-sitter/tree-sitter-julia"
aliases = ["jl"]

[[languages]]
name = "kotlin"
repo = "https://github.com/fwcd/tree-sitter-kotlin"
aliases = ["kt", "kts"]

[[languages]]
name = "latex"
repo = "https://github.com/latex-lsp/tree-sitter-latex"
aliases = ["tex"]

[[languages]]
name = "lua"
repo = "https://github.com/tjdevries/tree-sitter-lua"

[[languages]]
name = "make"
repo = "https://github.com/alemuller/tree-sitter-make"
aliases = ["mk", "makefile"]

[[languages]]
name = "matlab"
repo = "https://github.com/acristoffers/tree-sitter-matlab"
aliases = ["m"]

[[languages]]
name = "meson"
repo = "https://github.com/Decodetalkers/tree-sitter-meson"

[[languages]]
name = "nim"
repo = "https://github.com/aMOPel/tree-sitter-nim"

[[languages]]
name = "nix"
repo = "https://github.com/nix-community/tree-sitter-nix"

[[languages]]
name = "objc"
pretty_name = "ObjC"
repo = "https://github.com/jiyee/tree-sitter-objc"
aliases = ["objective-c", "objectivec", "obj-c"]

[[languages]]
name = "ocaml"
repo = "https://github.com/tree-sitter/tree-sitter-ocaml"
command = '''
set -euxo pipefail &&
git clone https://github.com/tree-sitter/tree-sitter-ocaml languages/temp/ocaml &&
cp languages/temp/ocaml/common/scanner.h languages/temp/ocaml/ocaml/src && 
sed -i -e 's/#include "\(.*\)"/#include "scanner.h"/g' languages/temp/ocaml/ocaml/src/scanner.c &&
cp -r languages/temp/ocaml/ocaml/src languages/temp/ocaml
'''
aliases = ["ml"]

[[languages]]
name = "ocaml_interface"
pretty_name = "OcamlInterface"
repo = "https://github.com/tree-sitter/tree-sitter-ocaml"
command = '''
set -euxo pipefail &&
git clone https://github.com/tree-sitter/tree-sitter-ocaml languages/temp/ocaml_interface &&
cp languages/temp/ocaml_interface/common/scanner.h languages/temp/ocaml_interface/interface/src && 
sed -i -e 's/#include "\(.*\)"/#include "scanner.h"/g' languages/temp/ocaml_interface/interface/src/scanner.c &&
cp -r languages/temp/ocaml_interface/interface/src languages/temp/ocaml_interface
'''
aliases = ["mli"]

[[languages]]
name = "openscad"
pretty_name = "OpenScad"
repo = "https://github.com/bollian/tree-sitter-openscad"
aliases = ["scad"]

[[languages]]
name = "pascal"
repo = "https://github.com/Isopod/tree-sitter-pascal"

[[languages]]
name = "perl"
repo = "https://github.com/ganezdragon/tree-sitter-perl"
aliases = ["pl"]

[[languages]]
name = "php"
repo = "https://github.com/tree-sitter/tree-sitter-php"

[[languages]]
name = "python"
repo = "https://github.com/tree-sitter/tree-sitter-python"
aliases = ["py"]

[[languages]]
name = "r"
repo = "https://github.com/r-lib/tree-sitter-r/"

[[languages]]
name = "regex"
repo = "https://github.com/tree-sitter/tree-sitter-regex"

[[languages]]
name = "ruby"
repo = "https://github.com/tree-sitter/tree-sitter-ruby"
aliases = ["rb"]

[[languages]]
name = "rust"
repo = "https://github.com/tree-sitter/tree-sitter-rust"
aliases = ["rs"]

[[languages]]
name = "scala"
repo = "https://github.com/tree-sitter/tree-sitter-scala"

[[languages]]
name = "scheme"
repo = "https://github.com/6cdh/tree-sitter-scheme"
aliases = ["scm", "ss"]

[[languages]]
name = "scss"
repo = "https://github.com/serenadeai/tree-sitter-scss"

[[languages]]
name = "sql"
repo = "https://github.com/DerekStride/tree-sitter-sql/tree/gh-pages"
command = "git clone --branch gh-pages https://github.com/DerekStride/tree-sitter-sql languages/temp/sql"

# Doesn't check in parser.c (extremely unhelpful)
# [[languages]]
# name = "swift"
# repo = "https://github.com/alex-pinkus/tree-sitter-swift"

[[languages]]
name = "toml"
repo = "https://github.com/tree-sitter/tree-sitter-toml"

[[languages]]
name = "typescript"
repo = "https://github.com/tree-sitter/tree-sitter-typescript"
# Disgusting hack to extract the non-TSX grammar, relocate the scanner header and patch the source file appropriately
# Words cannot describe how much I hate this, but it works
command = '''
set -euxo pipefail &&
git clone https://github.com/tree-sitter/tree-sitter-typescript languages/temp/typescript &&
cp languages/temp/typescript/common/scanner.h languages/temp/typescript/typescript/src && 
sed -i -e 's/#include "\(.*\)"/#include "scanner.h"/g' languages/temp/typescript/typescript/src/scanner.c &&
cp -r languages/temp/typescript/typescript/src languages/temp/typescript/
'''
aliases = ["ts"]

[[languages]]
name = "x86asm"
repo = "https://github.com/bearcove/tree-sitter-x86asm"
aliases = ["x86"]

[[languages]]
name = "yaml"
repo = "https://github.com/ikatyang/tree-sitter-yaml"

[[languages]]
name = "wgsl"
repo = "https://github.com/szebniok/tree-sitter-wgsl"

[[languages]]
name = "zig"
repo = "https://github.com/maxxnino/tree-sitter-zig"