//! Common constants.

/// The names recognized by `tree-sitter` when querying the parse tree during highlighting.
/// 
/// Sourced from the [Helix](https://docs.helix-editor.com/themes.html) project.
pub const HIGHLIGHT_NAMES: &[&str] = &[
    "attribute",
    "type",
    "type.builtin",
    "type.enum",
    "type.enum.variant",
    "constructor",
    "constant",
    "constant.builtin",
    "constant.builtin.boolean",
    "constant.character",
    "constant.character.escape",
    "constant.numeric",
    "constant.numeric.integer",
    "constant.numeric.float",
    "string",
    "string.regexp",
    "string.special",
    "string.special.path",
    "string.special.url",
    "string.special.symbol",
    "escape",
    "comment",
    "comment.line",
    "comment.block",
    "comment.block.documentation",
    "variable",
    "variable.builtin",
    "variable.parameter",
    "variable.other",
    "variable.other.member",
    "label",
    "punctuation",
    "punctuation.delimiter",
    "punctuation.bracket",
    "punction.special",
    "keyword",
    "keyword.control",
    "keyword.control.conditional",
    "keyword.control.repeat",
    "keyword.control.import",
    "keyword.control.return",
    "keyword.control.exception",
    "keyword.operator",
    "keyword.directive",
    "keyword.function",
    "keyword.storage",
    "keyword.storage.type",
    "keyword.storage.modifier",
    "operator",
    "function",
    "function.builtin",
    "function.method",
    "function.macro",
    "function.special",
    "tag",
    "tag.builtin",
    "namespace",
    "special",
    "diff",
    "diff.plus",
    "diff.minus",
    "diff.delta",
    "diff.delta.moved"
];

/// The same as [`HIGHLIGHT-NAMES`], but with all dots replaced with spaces.
pub const HIGHLIGHT_CLASS_NAMES: &[&str] = &[
    "attribute",
    "type",
    "type builtin",
    "type enum",
    "type enum variant",
    "constructor",
    "constant",
    "constant builtin",
    "constant builtin boolean",
    "constant character",
    "constant character escape",
    "constant numeric",
    "constant numeric integer",
    "constant numeric float",
    "string",
    "string regexp",
    "string special",
    "string special path",
    "string special url",
    "string special symbol",
    "escape",
    "comment",
    "comment line",
    "comment block",
    "comment block documentation",
    "variable",
    "variable builtin",
    "variable parameter",
    "variable other",
    "variable other member",
    "label",
    "punctuation",
    "punctuation delimiter",
    "punctuation bracket",
    "punction special",
    "keyword",
    "keyword control",
    "keyword control conditional",
    "keyword control repeat",
    "keyword control import",
    "keyword control return",
    "keyword control exception",
    "keyword operator",
    "keyword directive",
    "keyword function",
    "keyword storage",
    "keyword storage type",
    "keyword storage modifier",
    "operator",
    "function",
    "function builtin",
    "function method",
    "function macro",
    "function special",
    "tag",
    "tag builtin",
    "namespace",
    "special",
    "diff",
    "diff plus",
    "diff minus",
    "diff delta",
    "diff delta moved",
];